S18Team22-master/team22project/team22project/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using team22project.DAL;
using team22project.Models;

namespace team22project.Controllers
{
    public enum SortOrder { greater, lesser }

    public class MoviesController : Controller
    {
        private AppDbContext db = new AppDbContext();

        //// GET: Movies
        //public ActionResult Index()
        //{
        //    return View(db.Movies.ToList());
        //}

        public ActionResult Index(String SearchString)
        {
            List<Movie> SelectedMovies = new List<Movie>();

            //create query

            var query = from r in db.Movies

                        select r;

            //check to see if they selected something

            if (SearchString != null)
            {
                //if they selected a search string, limit results to only repos that meet the criteria
                query = query.Where(r => r.Title.Contains(SearchString) || r.Overview.Contains(SearchString) || r.Actors.Contains(SearchString) || r.Tagline.Contains(SearchString));
            }

            //execute query
            SelectedMovies = query.ToList();

            //order list
            SelectedMovies.OrderByDescending(r => r.ReleaseDate);

            ViewBag.TotalMovies = db.Movies.Count();

            ViewBag.SelectedMovies = SelectedMovies.Count();

            //send list to view
            return View(SelectedMovies);

        }

        // GET: Movies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        //GET: Showings/Details/5
        public ActionResult Showings(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            var newid = from m in db.Movies
                        select m;
            newid = newid.Where(m => m.Showings.Exists(x => x.Movie.MovieID == m.MovieID)/*(x => x.Movie.MovieID == m.MovieID)*/);
            Showing show = db.Showings.Find(newid);

            return View(show);
        }

        // GET: Movies/Create
        public ActionResult Create()
        {
            ViewBag.AllGenres = GetGenres();
            return View();
        }

        //POST: Movies/Create
        //To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MovieID,Title,Overview,Tagline,ReleaseDate,MPAARating,RunTime,Actor")] Movie movie, int[] SelectedGenre)
        {
            movie.MovieNumber = Utilities.GenerateNextMovieNumber.GetNextMovieNumber();

            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        // GET: Movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MovieID,Title,Tagline,ReleaseDate,MPAARating,RunTime")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public MultiSelectList GetAllGenres()

        {

            List<Genre> allGens = db.Genres.OrderBy(d => d.GenreName).ToList();

            MultiSelectList selGens = new MultiSelectList(allGens, "GenreID", "GenreName");

            return selGens;

        }

        public MultiSelectList GetAllGenres(Movie movie)

        {

            List<Genre> allGenres = db.Genres.OrderBy(d => d.GenreName).ToList();

            //convert list of selected departments to ints
            List<Int32> SelectedGenres = new List<Int32>();

            //loop through the course's departments and add the department id
            foreach (Genre gen in movie.Genres)

            {
                SelectedGenres.Add(gen.GenreID);
            }

            //create the multiselect list
            MultiSelectList selGens = new MultiSelectList(allGenres, "GenreID", "GenreName", SelectedGenres);

            //return the multiselect list
            return selGens;

        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult DetailedSearch()
        {
            ViewBag.AllGenres = GetGenres();
            return View();
        }

        public ActionResult DisplaySearchResults(bool ShowingOnly, String strTitle, String strTagline, Int32? intSelectedYear, MPAARating MPAArating, String strActors, Int32? SelectedGenre, DateTime? datSchedule)
        {
            //create query
            var query = from m in db.Movies
                        select m;
            if (ShowingOnly == true)
            {
                query = query.Where(m => m.Showings.Any(x => x.Movie.MovieID == m.MovieID));
            }

            //check to see if they selected something
            if (strTitle != null)
            {
                //if they selected a search string, limit results to only repos that meet the criteria
                query = query.Where(m => m.Title.Contains(strTitle));
            }

            if (strTagline != null)
            {
                query = query.Where(m => m.Tagline.Contains(strTagline));
            }

            if (intSelectedYear != null)
            {
                query = query.Where(m => m.ReleaseDate.Year == intSelectedYear);
            }
            if (MPAArating != MPAARating.Any)
            {
                if (MPAArating == MPAARating.G)
                {
                    query = query.Where(m => m.MPAARating == MPAARating.G);
                }
                if (MPAArating == MPAARating.PG)
                {
                    query = query.Where(m => m.MPAARating == MPAARating.PG);
                }
                if (MPAArating == MPAARating.PG13)
                {
                    query = query.Where(m => m.MPAARating == MPAARating.PG13);
                }
                if (MPAArating == MPAARating.R)
                {
                    query = query.Where(m => m.MPAARating == MPAARating.R);
                }
                if (MPAArating == MPAARating.Unrated)
                {
                    query = query.Where(m => m.MPAARating == MPAARating.Unrated);
                }
            }
            if (strActors != null)
            {
                query = query.Where(m => m.Actors.Contains(strActors));
            }

            if (SelectedGenre != null)
            {
                query = query.Where(m => m.Genres.Any(x => x.GenreID == SelectedGenre));
            }
            if (datSchedule != null)
            {
                query = query.Where(m => m.Showings.Any(x => x.Movie.MovieID == m.MovieID && x.ShowingDate == datSchedule));

            }


            //execute query
            List<Movie> MoviesToDisplay = query.ToList();
            ViewBag.TotalMovies = db.Movies.Count();
            ViewBag.SelectedMovies = MoviesToDisplay.Count();
            //order lsit
            //MoviesToDisplay.OrderByDescending(r => r.StarCount);
            
            if (MoviesToDisplay.Count == 0)
            {
                return View("NoMovies");
            }

            //send list to view
            return View("Index", MoviesToDisplay);

        }


        public MultiSelectList GetGenres()
        {
            List<Genre> Genres = db.Genres.ToList();

            Genre SelectNone = new Models.Genre();
            Genres.Add(SelectNone);

            MultiSelectList AllGenres = new MultiSelectList(Genres.OrderBy(m => m.GenreID), "GenreID", "GenreName");

            return AllGenres;
        }
    }
}

S18Team22-master/team22project/team22project/Controllers/ShowingsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using team22project.DAL;
using team22project.Models;

namespace team22project.Controllers
{
    public class ShowingsController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Showings
        public ActionResult Index()
        {
            return View(db.Showings.ToList());
        }

        // GET: Showings/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showing showing = db.Showings.Find(id);
            if (showing == null)
            {
                return HttpNotFound();
            }
            //ViewBag.GetAllSeats = AvailableSeats();
            return View(showing);
        }

        public SelectList GetAllMovies()
        {
            List<Movie> allMovies = db.Movies.OrderBy(p => p.Title).ToList();

            SelectList selMovies = new SelectList(allMovies, "MovieID", "Title");

            return selMovies;
        }

        // GET: Showings/Create
        public ActionResult Create()
        {
            ViewBag.AllMovies = GetAllMovies();
            return View();
        }

        // POST: Showings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ShowingID,ShowingDate,StartTime,Theatre,SpecialEvent")] Showing showing, int SelectedMovie)
        {
            
            if (ModelState.IsValid)
            {
                db.Showings.Add(showing);
                Movie m = db.Movies.Find(SelectedMovie);
                showing.Movie = m;
                showing.DayOfWeek = showing.ShowingDate.DayOfWeek;
                showing.Display = showing.ShowingDate.ToLocalTime();
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(showing);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult AddToOrder(Transaction tran, Showing show, string[] AvailableSeats)
        //{

        //    if (ModelState.IsValid)
        //    {
        //        db.Showings.Add(showing);
        //        Movie m = db.Movies.Find(SelectedMovie);
        //        showing.Movie = m;
        //        showing.DayOfWeek = showing.ShowingDate.DayOfWeek;
        //        showing.Display = showing.ShowingDate.ToLocalTime();
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(showing);
        //}

        // GET: Showings/Edit/5

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showing showing = db.Showings.Find(id);
            if (showing == null)
            {
                return HttpNotFound();
            }
            return View(showing);
        }

        // POST: Showings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Manager")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ShowingID,Movie,ShowingDate,TimeofWeek,Theatre,SpecialEvent")] Showing showing)
        {
            if (ModelState.IsValid)
            {
                db.Entry(showing).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(showing);
        }

        // GET: Showings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Showing showing = db.Showings.Find(id);
            if (showing == null)
            {
                return HttpNotFound();
            }
            return View(showing);
        }

        // POST: Showings/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Manager")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Showing showing = db.Showings.Find(id);
            db.Showings.Remove(showing);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public static SelectList AvailableSeats(List<Ticket> Tickets)
        {
            List<String> TakenSeatNames = new List<String>();
            foreach (Ticket t in Tickets)
            {
                TakenSeatNames.Add(t.Seat);
            }

            List<String> AllSeatNames = new List<String>();
            AllSeatNames.Add("A1");
            AllSeatNames.Add("A2");
            AllSeatNames.Add("A3");
            AllSeatNames.Add("A4");
            AllSeatNames.Add("A5");
            AllSeatNames.Add("A6");
            AllSeatNames.Add("A7");
            AllSeatNames.Add("A8");
            AllSeatNames.Add("B1");
            AllSeatNames.Add("B2");
            AllSeatNames.Add("B3");
            AllSeatNames.Add("B4");
            AllSeatNames.Add("B5");
            AllSeatNames.Add("B6");
            AllSeatNames.Add("B7");
            AllSeatNames.Add("B8");
            AllSeatNames.Add("C1");
            AllSeatNames.Add("C2");
            AllSeatNames.Add("C3");
            AllSeatNames.Add("C4");
            AllSeatNames.Add("C5");
            AllSeatNames.Add("C6");
            AllSeatNames.Add("C7");
            AllSeatNames.Add("C8");
            AllSeatNames.Add("D1");
            AllSeatNames.Add("D2");
            AllSeatNames.Add("D3");
            AllSeatNames.Add("D4");
            AllSeatNames.Add("D5");
            AllSeatNames.Add("D6");
            AllSeatNames.Add("D7");
            AllSeatNames.Add("D8");


            List<String> AvailableSeats = AllSeatNames.Except(TakenSeatNames).ToList();

            SelectList slAvailableSeats = new SelectList(AvailableSeats);

            return slAvailableSeats;
        }

        //public MultiSelectList GetAllSeats()
        //{
        //    List<Seat> allSeats = db.Seats.OrderBy(d => d.SeatName).ToList();

        //    MultiSelectList selSeats = new MultiSelectList(allSeats, "SeatID", "SeatName");

        //    return selSeats;
        //}


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

S18Team22-master/team22project/team22project/Views/Movies/Create.cshtml
@model team22project.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <p class="form-group">
                @Html.DisplayName("Select Genre(s):")<br />
                @Html.ListBox("SelectedGenre", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
                <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Overview, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Overview, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Overview, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tagline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tagline, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tagline, "", new { @class = "text-danger" })
            </div>
        </div>

            Release Date:<input type="date" name="ReleaseDate" class="form-control" /> <br />


        <div class="form-group">
            @Html.LabelFor(model => model.MPAARating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.MPAARating, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MPAARating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RunTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Actors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Actors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Actors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

S18Team22-master/team22project/team22project/Views/Movies/Delete.cshtml
@model team22project.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tagline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tagline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MPAARating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MPAARating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RunTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

S18Team22-master/team22project/team22project/Views/Movies/DetailedSearch.cshtml
@using team22project.Controllers
@using team22project.Models
@{
    /**/

    ViewBag.Title = "DetailedSearch";
}

<h2>Detailed Search</h2>

@using (Html.BeginForm("DisplaySearchResults", "Movies", FormMethod.Get))
{
<p class="form-group">
    <label class="radio">@Html.RadioButton("ShowingOnly", true, true) Currently Showing Movies</label>
    </p>
    <p>
    <label class="radio">@Html.RadioButton("ShowingOnly", false) All Movies</label>
</p>
    <p class="form-group">
        Search Movie Title: @Html.TextBox("strTitle", null, new { @class = "form-control" })
        <br />
    </p>
    <p class="form-group">
        Search Tagline: @Html.TextBox("strTagline", null, new { @class = "form-control" })
        <br />
    </p>
    <p class="form-group">
        Select Release Year: @Html.TextBox("intSelectedYear", null, new { @class = "form-control" })
        <br />
    </p>
    <p class="form-group">
        MPAA Rating:
    </p>
    <p>
        <label class="radio">@Html.RadioButton("MPAARating", MPAARating.Any, true) Any</label>
        <label class="radio">@Html.RadioButton("MPAARating", MPAARating.G) G</label>
        <label class="radio">@Html.RadioButton("MPAARating", MPAARating.PG) PG</label>
        <label class="radio">@Html.RadioButton("MPAARating", MPAARating.PG13) PG13</label>
        <label class="radio">@Html.RadioButton("MPAARating", MPAARating.R) R</label>
        <label class="radio">@Html.RadioButton("MPAARating", MPAARating.Unrated) Unrated</label>
        <br />
    </p>
    <p class="form-group">
        Search Actors: @Html.TextBox("strActors", null, new { @class = "form-control" })
        <br />
    </p>
    <p class="form-group">
        Search Genres: @Html.ListBox("SelectedGenre", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
        <br />
    </p>
    <p>
        Showing Day:<input type="date" name="datSchedule" class="form-control" />
    </p>


    <p class="form-group">
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}

S18Team22-master/team22project/team22project/Views/Movies/Details.cshtml
@model team22project.Models.Movie
@using team22project.Models

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Title)</h2>

<div>
    @*<h4> Details</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>

        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tagline)
        </dd>

        <dt>
            <span>CAST</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Actors)
        </dd>

        <dt>
            <span>GENRES</span>
        </dt>

        <dd>
            @foreach (Genre genre in Model.Genres)

        {
            @Html.DisplayFor(modelItem => genre.GenreName)<span> | </span>
    }
        </dd>

        <dt>
            @Html.DisplayFor(model => model.MPAARating)
        </dt>

        <dd>
            <span>OVERVIEW - </span>@Html.DisplayFor(model => model.Overview)
        </dd>

        <dd>
            @Html.DisplayNameFor(model => model.ReleaseDate)<span> - </span>@Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dd>
            @Html.DisplayNameFor(model => model.Revenue)<span> - </span>@Html.DisplayFor(model => model.Revenue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RunTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Showings)
        </dt>
        @foreach (Showing showing in Model.Showings)
    {
        <dd>
            @Html.DisplayFor(modelItem => showing.Display)<span> - @Html.ActionLink("Find Tickets", "Create", "Transactions", new { id = showing.ShowingID }, null)</span>
        </dd>
}


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MovieID }) |
    @Html.ActionLink("Back to List", "Index")
    @*@Html.ActionLink("User List", "Details", "Showings", new { querystringparameter = Model.MovieID }, null)*@
</p>

S18Team22-master/team22project/team22project/Views/Movies/Edit.cshtml
@model team22project.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MovieID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <p class="form-group">
                    @Html.DisplayName("Select Genre(s):")<br />
                    @Html.ListBox("SelectedGenre", (MultiSelectList)ViewBag.AllGenres, new { @class = "form-control" })
                    <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Overview, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Overview, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Overview, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tagline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tagline, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tagline, "", new { @class = "text-danger" })
            </div>
        </div>

          Release Date:<input type="date" name="ReleaseDate" class="form-control" /> <br />


        <div class="form-group">
            @Html.LabelFor(model => model.MPAARating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.MPAARating, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MPAARating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RunTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RunTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

S18Team22-master/team22project/team22project/Views/Movies/NoMovies.cshtml
@{
    ViewBag.Title = "NoMovies";
}

<h2>There aint no movies that matches that query lol</h2>